/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 paraglider-orange.glb -T 
Files: paraglider-orange.glb [3.54MB] > D:\Test Project\paragliding\public\models\paraglider-orange-transformed.glb [360.64KB] (90%)
*/

import React, { useRef, useImperativeHandle, forwardRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";
import { useMediaQuery } from "react-responsive";

interface ParagliderModelProps {
  scale: number;
}

export const ParagliderModel = forwardRef<ParagliderModelProps>(
  ({ ...props }, ref) => {
    const isMobile = useMediaQuery({ maxWidth: 430 });
    const isTablet = useMediaQuery({ maxWidth: 1000 });
    const { nodes, materials } = useGLTF(
      "/models/paraglider-orange-transformed.glb"
    );
    return (
      <group
        scale={isMobile ? 0.08 : isTablet ? 0.1 : 0.15}
        {...props}
        dispose={null}
      >
        <mesh
          geometry={(nodes.Mesh_0 as THREE.Mesh).geometry}
          material={materials["Material.001"]}
          position={[-1.044, -8.672, -0.12]}
          rotation={[0, 1.509, 0]}
          scale={3}
        />
        <mesh
          geometry={(nodes.Parachute_skinnedmo as THREE.Mesh).geometry}
          material={materials.Material}
          position={[-1.178, -8.358, -0.15]}
          scale={[0.045, 0.045, 0.063]}
        />
      </group>
    );
  }
);

ParagliderModel.displayName = "ParagliderModel";
useGLTF.preload("/models/paraglider-orange-transformed.glb");
