/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 paraglider.glb -T 
Files: paraglider.glb [6.1MB] > D:\Test Project\paragliding\public\models\paraglider-transformed.glb [432.3KB] (93%)
*/

import React, { useRef, useImperativeHandle, forwardRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";
// 1. Define the custom interface for the properties GSAP will target
// export interface ModelHandle {
//   scrollProgress: number;
// }

// 2. Define the types for the model properties
interface ParagliderModelProps {
  scale: number;
  // onReady?: (ready: boolean) => void; // Optional ready prop
}

export const ParagliderModel = forwardRef<ParagliderModelProps>(
  ({ ...props }, ref) => {
    const { nodes, materials } = useGLTF("/models/paraglider-transformed.glb");

    return (
      <group scale={0.15} {...props} dispose={null}>
        <mesh
          geometry={(nodes.Mesh_0 as THREE.Mesh).geometry}
          material={materials["Material.001"]}
          position={[-1.044, -8.672, -0.12]}
          rotation={[0, 1.509, 0]}
          scale={3}
        />
        <mesh
          geometry={(nodes.Parachute_skinnedmo as THREE.Mesh).geometry}
          material={materials.Material}
          position={[-1.178, -8.358, -0.15]}
          scale={[0.045, 0.045, 0.063]}
        />
      </group>
    );
  }
);

ParagliderModel.displayName = "ParagliderModel";
useGLTF.preload("/models/paraglider-transformed.glb");
